export const AAT_INTERACTION_CONSTANTS = {
  PERSONALIZE_BY_FIRST_NAME: true,
  ASK_REASON_AFTER_AUTO_LOGOUT: true,
  ASK_DISTRACTION_AFTER_AUTO_LOGOUT: true,
  PRESERVE_INTERRUPTION_HISTORY: true,
};
