export const ENGAGEMENT_CONSTANTS = {
  REGULAR_CHECK_INTERVAL_SECONDS: 300,
  FOLLOW_UP_CHECK_INTERVAL_SECONDS: 10,
  MAX_CONSECUTIVE_MISSED_CHECKS: 3,
  FOLLOW_UP_CHECKS_AFTER_NON_RESPONSE: 2,
  AUTO_LOGOUT_ON_THRESHOLD: true,
  STAR_FORFEIT_ON_AUTO_LOGOUT: true,
};
