export const LEARNING_CONSTANTS = {
  DEFAULT_DSC_SUBJECTS: 4,
  MAX_DSC_SUBJECTS: 12,
  VALID_DSC_SUBJECTS: [4, 6, 8, 10, 12],
  LESSON_DURATION_MINUTES: 25,
  REVISION_DURATION_MINUTES: 5,
  QUIZ_DURATION_MINUTES: 10,
  AI_CHECK_INTERVAL_MINUTES: 5,
  MAX_CONSECUTIVE_MISSED_RESPONSES: 2,
  AUTO_LOGOUT_ON_THIRD_MISSED_RESPONSE: true,
  STARS_PER_FOUR_SUBJECTS: 2,
  MINIMUM_AWARD_SCORE_PERCENT: 80,
};
