export const RUNTIME_CONSTANTS = {
  DELIVERY_REQUIRED: true,
  ORCHESTRATION_REQUIRED: true,
  SESSION_REQUIRED: true,
  PERSISTENCE_REQUIRED: true,

  AUTO_SNAPSHOT_ON_STATE_CHANGE: true,

  RESUME_FROM_PERSISTED_STATE: true,

  QUESTION_MODE_PERSISTENCE_REQUIRED: true,

  CBT_COMPLETION_PERSISTENCE_REQUIRED: true,

  STARS_ELIGIBILITY_PERSISTENCE_REQUIRED: true,

  OFFLINE_RUNTIME_SUPPORTED: true,
};
