export const PERSISTENCE_CONSTANTS = {
  OFFLINE_SNAPSHOT_ENABLED: true,

  AUTO_SAVE_ENABLED: true,

  RESUME_ENABLED: true,

  LAST_KNOWN_STATE_ENABLED: true,

  LAST_KNOWN_POSITION_ENABLED: true,

  QUESTION_MODE_SNAPSHOT_ENABLED: true,

  CBT_STATE_SNAPSHOT_ENABLED: true,

  STAR_ELIGIBILITY_SNAPSHOT_ENABLED: true,

  MAX_SNAPSHOTS_PER_SESSION: 20,
};
