export const LEARNING_ENGINE_CONSTANTS = {
  DELIVERY_REQUIRED: true,
  ORCHESTRATION_REQUIRED: true,
  SESSION_REQUIRED: true,
  PERSISTENCE_REQUIRED: true,
  RUNTIME_REQUIRED: true,
  CROSS_BINDING_REQUIRED: true,

  CREATE_SESSION_BEFORE_LEARNING: true,
  LOAD_STATE_BEFORE_RESUME: true,
  PERSIST_STATE_AFTER_TRANSITION: true,
  PERSIST_POSITION_UPDATES: true,
  PERSIST_QUESTION_MODE: true,
  PERSIST_LESSON_COMPLETION: true,
  PERSIST_CBT_COMPLETION: true,

  OFFLINE_FIRST_EXECUTION: true,
};
