export enum SubscriptionNotificationType {
  EXPIRY_7_DAYS = 'EXPIRY_7_DAYS',
  EXPIRY_3_DAYS = 'EXPIRY_3_DAYS',
  EXPIRY_24_HOURS = 'EXPIRY_24_HOURS',
  EXPIRED = 'EXPIRED',
  RENEWAL_REMINDER = 'RENEWAL_REMINDER',
}
