export enum TrialNotificationType {
  WELCOME = 'WELCOME',
  REMAINING_72H = 'REMAINING_72H',
  REMAINING_24H = 'REMAINING_24H',
  REMAINING_6H = 'REMAINING_6H',
  REMAINING_1H = 'REMAINING_1H',
  EXPIRED = 'EXPIRED',
}
