export const ORCHESTRATION_CONSTANTS = {

  TCC_REQUIRED: true,

  DSC_REQUIRED: true,

  CONTENT_REQUIRED: true,

  LESSON_REQUIRED_BEFORE_CBT: true,

  CBT_REQUIRED_BEFORE_STARS: true,

  QUESTION_MODE_RETURN_ENABLED: true,

  OFFLINE_FLOW_SUPPORTED: true,

};
