export enum LearningEngineState {
  READY = 'READY',
  INITIALIZING = 'INITIALIZING',
  DELIVERY_READY = 'DELIVERY_READY',
  SESSION_READY = 'SESSION_READY',
  LEARNING_ACTIVE = 'LEARNING_ACTIVE',
  QUESTION_MODE = 'QUESTION_MODE',
  LESSON_COMPLETED = 'LESSON_COMPLETED',
  CBT_ACTIVE = 'CBT_ACTIVE',
  CBT_COMPLETED = 'CBT_COMPLETED',
  RESUMING = 'RESUMING',
  COMPLETED = 'COMPLETED',
  BLOCKED = 'BLOCKED',
}
