export const CROSS_BINDING_CONSTANTS = {
  DELIVERY_ENGINE_REQUIRED: true,

  ORCHESTRATION_ENGINE_REQUIRED: true,

  SESSION_ENGINE_REQUIRED: true,

  PERSISTENCE_ENGINE_REQUIRED: true,

  RUNTIME_ENGINE_REQUIRED: true,

  DELIVERY_BEFORE_ORCHESTRATION: true,

  ORCHESTRATION_BEFORE_SESSION: true,

  SESSION_BEFORE_RUNTIME: true,

  RUNTIME_STATE_PERSISTENCE_REQUIRED: true,

  QUESTION_MODE_STATE_PERSISTENCE_REQUIRED: true,

  LESSON_COMPLETION_STATE_PERSISTENCE_REQUIRED: true,

  CBT_COMPLETION_STATE_PERSISTENCE_REQUIRED: true,

  STARS_ELIGIBILITY_STATE_PERSISTENCE_REQUIRED: true,

  OFFLINE_CHAIN_SUPPORTED: true,
};
