export const SCHEDULING_CONSTANTS = {
  DAYS_PER_WEEK: 7,

  NORMAL_SUBJECTS_PER_DAY: 5,

  MAX_SUBJECTS_PER_TERM: 14,

  EXAM_SUBJECTS_PER_DAY: 2,

  EXAMINATION_WEEK_IS_LAST_WEEK: true,

  CONTINUOUS_OPERATION: true,

  REST_DAYS_ALLOWED: false,

  VACATION_DAYS_AUTOMATIC: false,

  BALANCED_WEEKLY_DISTRIBUTION: true,

  CURRICULUM_COMPLIANCE_REQUIRED: true,
};
