export const CURRICULUM_CONSTANTS = {
  LESSON_DURATION_MINUTES: 25,
  REVISION_DURATION_MINUTES: 5,
  CBT_DURATION_MINUTES: 10,
  TOTAL_SUBJECT_SESSION_MINUTES: 40,

  TERMS_PER_SESSION: 3,
  MONTHS_PER_TERM: 4,

  MONTHLY_ASSESSMENT_LAST_WEEK: true,

  DAILY_EXAM_SUBJECT_COUNT: 2,

  CBT_EXAM_QUESTIONS: 50,
  CBT_EXAM_MARKS: 25,

  ESSAY_QUESTIONS_SET: 7,
  ESSAY_QUESTIONS_TO_ANSWER: 5,
  ESSAY_MARKS: 50,

  HOMEWORK_MARKS: 25,

  FAST_FORWARD_ALLOWED: false,
  REPLAY_ALLOWED_SCHOOL_LESSON: false,
  PAUSE_ALLOWED: true,
  EXIT_CAUSES_LOGOUT: true,
  EXIT_FORFEITS_STARS: true,
};
