export const DSC_CONSTANTS = {
  DAILY_SUBJECTS: 5,
  LESSON_MINUTES: 32,
  REVISION_MINUTES: 3,
  CBT_MINUTES: 5,

  DAYS_PER_WEEK: 7,
  WEEKS_PER_TERM: 16,

  MONTHLY_ASSESSMENT_LAST_WEEK: true,

  TOPIC_SKIP_ALLOWED: false,
  BALANCED_TOPIC_DISTRIBUTION: true,

  RECOVERY_ENABLED: true,
};
