export const DSC_CONSTANTS = {
  DAILY_SUBJECTS: 4,
  LESSON_MINUTES: 25,
  REVISION_MINUTES: 5,
  CBT_MINUTES: 10,

  DAYS_PER_WEEK: 5,
  WEEKS_PER_TERM: 16,

  MONTHLY_ASSESSMENT_LAST_WEEK: true,

  TOPIC_SKIP_ALLOWED: false,
  BALANCED_TOPIC_DISTRIBUTION: true,

  RECOVERY_ENABLED: true,
};
