export const GATEWAY_CONSTANTS = {
  DELIVERY_POLICY_REQUIRED: true,
  ORCHESTRATION_POLICY_REQUIRED: true,
  SESSION_STATE_REQUIRED: true,
  PERSISTENCE_REQUIRED: true,

  CREATE_SESSION_BEFORE_DELIVERY: true,

  LOAD_PERSISTED_STATE_ON_RESUME: true,

  SNAPSHOT_ON_POSITION_UPDATE: true,

  SNAPSHOT_ON_QUESTION_MODE: true,

  SNAPSHOT_ON_LESSON_COMPLETION: true,

  SNAPSHOT_ON_CBT_COMPLETION: true,

  OFFLINE_EXECUTION_SUPPORTED: true,
};
