export enum GatewayState {
  READY = 'READY',
  SESSION_INITIALIZED = 'SESSION_INITIALIZED',
  DELIVERY_READY = 'DELIVERY_READY',
  LESSON_ACTIVE = 'LESSON_ACTIVE',
  QUESTION_MODE = 'QUESTION_MODE',
  LESSON_COMPLETED = 'LESSON_COMPLETED',
  CBT_ACTIVE = 'CBT_ACTIVE',
  CBT_COMPLETED = 'CBT_COMPLETED',
  RESUMED = 'RESUMED',
  COMPLETED = 'COMPLETED',
}
