import { LearningRuntimeDirectiveService } from './learning-runtime-directive.service';

describe('LearningRuntimeDirectiveService', () => {
  const service = new LearningRuntimeDirectiveService();

  it('converts a personalized learning path into an executable runtime directive', () => {
    const result = service.create({
      learningPath: {
        learnerId: 'learner-1',
        examinationType: 'WASSCE',
        generatedAt: '2026-08-10T00:00:00.000Z',
        version: 1,
        currentSubjectId: 'mathematics',
        currentTopicId: 'algebra',
        completionPercent: 40,
        nextAction: 'PRACTICE',
        subjects: [],
      },
    });

    expect(result).toEqual(
      expect.objectContaining({
        learnerId: 'learner-1',
        examinationType: 'WASSCE',
        subjectId: 'mathematics',
        topicId: 'algebra',
        action: 'PRACTICE',
        pathVersion: 1,
      }),
    );
  });

  it('preserves the runtime action generated by the learning path engine', () => {
    const result = service.create({
      learningPath: {
        learnerId: 'learner-2',
        examinationType: 'BECE',
        generatedAt: '2026-08-10T00:00:00.000Z',
        version: 1,
        currentSubjectId: 'english',
        currentTopicId: 'grammar',
        completionPercent: 80,
        nextAction: 'ASSESS',
        subjects: [],
      },
    });

    expect(result.action).toBe('ASSESS');
    expect(result.subjectId).toBe('english');
    expect(result.topicId).toBe('grammar');
  });
});
