export const SESSION_CONSTANTS = {
  SESSION_EXPIRY_MINUTES: 120,

  AUTO_SAVE_ENABLED: true,

  PAUSE_STATE_PERSISTENCE_ENABLED: true,

  QUESTION_MODE_POSITION_PRESERVATION: true,

  RESUME_FROM_LAST_POSITION: true,

  OFFLINE_SESSION_STATE_ENABLED: true,

  LESSON_POSITION_MIN: 0,

  LESSON_POSITION_MAX: 100,

  STAR_ELIGIBILITY_ON_CBT_COMPLETION: true,
};
