export const EXAM_CONSTANTS = {
  DAILY_SUBJECTS: 2,

  MAX_EXAM_DURATION_MINUTES: 90,

  CBT_QUESTIONS: 50,
  CBT_MARKS: 25,

  ESSAY_QUESTIONS_PROVIDED: 7,
  ESSAY_QUESTIONS_REQUIRED: 5,
  ESSAY_MARKS: 50,

  HOMEWORK_MARKS: 25,

  MONTHLY_ASSESSMENT_LAST_WEEK: true,

  RANDOMIZE_QUESTIONS: true,
  ANTI_CHEAT_ENABLED: true,

  PAUSE_ALLOWED: false,
  EXIT_ALLOWED: false,
  REPLAY_ALLOWED: false,

  AUTO_SUBMIT_ON_TIMEOUT: true,
};
