export const INTEGRATION_CONSTANTS = {

  TCC_TOPIC_REQUIRED: true,

  DSC_MUST_FOLLOW_TCC: true,

  CONTENT_REQUIRED_BEFORE_LESSON: true,

  LESSON_COMPLETION_REQUIRED_FOR_CBT: true,

  CBT_COMPLETION_REQUIRED_FOR_STARS: true,

  QUESTION_MODE_RETURN_ENABLED: true,

};
