export enum EducationLevel {
  PRIMARY = 'PRIMARY',
  JUNIOR_SECONDARY = 'JUNIOR_SECONDARY',
  SENIOR_SECONDARY = 'SENIOR_SECONDARY',
  ADULT_EDUCATION = 'ADULT_EDUCATION',
  SAP = 'SAP',
  BUSINESS_MODELLING = 'BUSINESS_MODELLING',
}
