export const SAP_CONSTANTS = {
  SAP_ENABLED: true,

  OFFLINE_FIRST: true,

  ASSESSMENT_REQUIRED: true,

  BASELINE_ASSESSMENT_REQUIRED: true,

  CONTINUOUS_ASSESSMENT_SUPPORTED: true,

  LEARNING_PROFILE_REQUIRED: true,

  COMPETENCY_TRACKING_REQUIRED: true,

  MASTERY_TRACKING_REQUIRED: true,

  LEARNING_GAP_ANALYSIS_REQUIRED: true,

  PERSONALIZED_PATH_REQUIRED: true,

  INTERVENTION_SUPPORTED: true,

  PROGRESS_TRACKING_REQUIRED: true,

  REPORTING_REQUIRED: true,

  PERSISTENCE_REQUIRED: true,

  LEARNING_ENGINE_BINDING_REQUIRED: true,

  SESSION_BINDING_REQUIRED: true,

  CBT_BINDING_SUPPORTED: true,

  OFFLINE_ASSESSMENT_SUPPORTED: true,

  SYNC_PENDING_SUPPORTED: true,

  MIN_MASTERY_SCORE: 70,

  MAX_ASSESSMENT_SCORE: 100,
};
