export const DELIVERY_CONSTANTS = {
  LESSON_DURATION_MINUTES: 25,
  REVISION_DURATION_MINUTES: 5,
  CBT_DURATION_MINUTES: 10,

  PLAY_ENABLED: true,
  PAUSE_ENABLED: true,
  FAST_FORWARD_ENABLED: false,
  REPLAY_ENABLED_SCHOOL_LESSON: false,

  QUESTION_MODE_ENABLED: true,
  RETURN_TO_LESSON_POSITION: true,

  OFFLINE_AI_CONTENT_ENABLED: true,
};
