export enum ProgrammeCategory {
  PRIMARY = 'PRIMARY',
  JUNIOR_SECONDARY = 'JUNIOR_SECONDARY',
  SENIOR_SECONDARY = 'SENIOR_SECONDARY',

  CERTIFICATE_EXAMINATION = 'CERTIFICATE_EXAMINATION',

  ADULT_EDUCATION = 'ADULT_EDUCATION',

  SAP = 'SAP',

  BUSINESS_MODELLING = 'BUSINESS_MODELLING',
}
