export enum WalletTransactionSource {
  SUBSCRIPTION = 'SUBSCRIPTION',
  USER = 'USER',
  REFERRAL = 'REFERRAL',
  PROMOTION = 'PROMOTION',
  ADMINISTRATION = 'ADMINISTRATION',
  LEARNING = 'LEARNING',
}
