export enum WalletTransactionType {
  SUBSCRIPTION_ALLOCATION = 'SUBSCRIPTION_ALLOCATION',
  WALLET_FUNDING = 'WALLET_FUNDING',

  LEARNING_CONSUMPTION = 'LEARNING_CONSUMPTION',

  REFERRAL_BONUS = 'REFERRAL_BONUS',
  PROMOTIONAL_BONUS = 'PROMOTIONAL_BONUS',

  MANUAL_ADJUSTMENT_CREDIT = 'MANUAL_ADJUSTMENT_CREDIT',
  MANUAL_ADJUSTMENT_DEBIT = 'MANUAL_ADJUSTMENT_DEBIT',
}
