export enum RuntimeState {
  READY = 'READY',
  SESSION_CREATED = 'SESSION_CREATED',
  LESSON_ACTIVE = 'LESSON_ACTIVE',
  QUESTION_MODE = 'QUESTION_MODE',
  LESSON_COMPLETED = 'LESSON_COMPLETED',
  CBT_ACTIVE = 'CBT_ACTIVE',
  CBT_COMPLETED = 'CBT_COMPLETED',
  RESUMED = 'RESUMED',
  COMPLETED = 'COMPLETED',
}
