export enum EngineBindingState {
  UNBOUND = 'UNBOUND',

  DELIVERY_BOUND = 'DELIVERY_BOUND',

  ORCHESTRATION_BOUND = 'ORCHESTRATION_BOUND',

  SESSION_BOUND = 'SESSION_BOUND',

  PERSISTENCE_BOUND = 'PERSISTENCE_BOUND',

  RUNTIME_BOUND = 'RUNTIME_BOUND',

  FULLY_BOUND = 'FULLY_BOUND',

  BLOCKED = 'BLOCKED',
}
