export enum SessionState {
  CREATED = 'CREATED',
  PLAYING = 'PLAYING',
  PAUSED = 'PAUSED',
  QUESTION_MODE = 'QUESTION_MODE',
  REVISION_MODE = 'REVISION_MODE',
  CBT_MODE = 'CBT_MODE',
  COMPLETED = 'COMPLETED',
  EXPIRED = 'EXPIRED',
}
